# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 332)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 160, 536, 29))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_close = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.btn_openCamera = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_openCamera.setObjectName("btn_openCamera")
        self.horizontalLayout.addWidget(self.btn_openCamera)
        self.btn_CF = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_CF.setObjectName("btn_CF")
        self.horizontalLayout.addWidget(self.btn_CF)
        self.btn_misaic = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_misaic.setObjectName("btn_misaic")
        self.horizontalLayout.addWidget(self.btn_misaic)
        self.btn_medianBlur = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_medianBlur.setObjectName("btn_medianBlur")
        self.horizontalLayout.addWidget(self.btn_medianBlur)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 521, 131))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(11, 11, 0, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.webCam = QtWidgets.QLabel(self.layoutWidget1)
        self.webCam.setObjectName("webCam")
        self.gridLayout.addWidget(self.webCam, 0, 0, 1, 1)
        self.captrue = QtWidgets.QLabel(self.layoutWidget1)
        self.captrue.setObjectName("captrue")
        self.gridLayout.addWidget(self.captrue, 0, 1, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 200, 521, 33))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_gray = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_gray.setObjectName("btn_gray")
        self.horizontalLayout_2.addWidget(self.btn_gray)
        self.btn_binary = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_binary.setObjectName("btn_binary")
        self.horizontalLayout_2.addWidget(self.btn_binary)
        self.sld_masaiko = QtWidgets.QSlider(self.layoutWidget2)
        self.sld_masaiko.setMinimum(1)
        self.sld_masaiko.setProperty("value", 37)
        self.sld_masaiko.setOrientation(QtCore.Qt.Horizontal)
        self.sld_masaiko.setObjectName("sld_masaiko")
        self.horizontalLayout_2.addWidget(self.sld_masaiko)
        self.sld_blur = QtWidgets.QSlider(self.layoutWidget2)
        self.sld_blur.setMinimum(3)
        self.sld_blur.setSingleStep(2)
        self.sld_blur.setOrientation(QtCore.Qt.Horizontal)
        self.sld_blur.setObjectName("sld_blur")
        self.horizontalLayout_2.addWidget(self.sld_blur)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.lab_blockSize = QtWidgets.QLabel(self.centralWidget)
        self.lab_blockSize.setGeometry(QtCore.QRect(220, 240, 131, 17))
        self.lab_blockSize.setObjectName("lab_blockSize")
        self.lab_blurSize = QtWidgets.QLabel(self.centralWidget)
        self.lab_blurSize.setGeometry(QtCore.QRect(420, 240, 81, 17))
        self.lab_blurSize.setObjectName("lab_blurSize")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 587, 25))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_close.setText(_translate("MainWindow", "Close"))
        self.btn_openCamera.setText(_translate("MainWindow", "OpenCamera"))
        self.btn_CF.setText(_translate("MainWindow", "Capture Frame"))
        self.btn_misaic.setText(_translate("MainWindow", "masaiko"))
        self.btn_medianBlur.setText(_translate("MainWindow", "medianBlur"))
        self.webCam.setText(_translate("MainWindow", "WebCam"))
        self.captrue.setText(_translate("MainWindow", "Capture"))
        self.btn_gray.setText(_translate("MainWindow", "Gray"))
        self.btn_binary.setText(_translate("MainWindow", "Binary"))
        self.lab_blockSize.setText(_translate("MainWindow", "TextLabel"))
        self.lab_blurSize.setText(_translate("MainWindow", "TextLabel"))

