# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddQuestion.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Add_Edit_Question_Page_UI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(907, 512)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 901, 471))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_question_list = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_question_list.setAlignment(QtCore.Qt.AlignCenter)
        self.label_question_list.setObjectName("label_question_list")
        self.gridLayout.addWidget(self.label_question_list, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_question_0 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_question_0.setObjectName("comboBox_question_0")
        self.gridLayout_2.addWidget(self.comboBox_question_0, 1, 0, 1, 1)
        self.label_question_type_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_question_type_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_question_type_3.setObjectName("label_question_type_3")
        self.gridLayout_2.addWidget(self.label_question_type_3, 0, 3, 1, 1)
        self.label_question_type_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_question_type_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_question_type_1.setObjectName("label_question_type_1")
        self.gridLayout_2.addWidget(self.label_question_type_1, 0, 1, 1, 1)
        self.label_question_type_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_question_type_0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_question_type_0.setObjectName("label_question_type_0")
        self.gridLayout_2.addWidget(self.label_question_type_0, 0, 0, 1, 1)
        self.label_question_type_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_question_type_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_question_type_2.setObjectName("label_question_type_2")
        self.gridLayout_2.addWidget(self.label_question_type_2, 0, 2, 1, 1)
        self.label_question_type_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_question_type_4.setObjectName("label_question_type_4")
        self.gridLayout_2.addWidget(self.label_question_type_4, 0, 4, 1, 1)
        self.comboBox_question_1 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_question_1.setObjectName("comboBox_question_1")
        self.gridLayout_2.addWidget(self.comboBox_question_1, 1, 1, 1, 1)
        self.comboBox_question_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_question_2.setObjectName("comboBox_question_2")
        self.gridLayout_2.addWidget(self.comboBox_question_2, 1, 2, 1, 1)
        self.comboBox_question_3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_question_3.setObjectName("comboBox_question_3")
        self.gridLayout_2.addWidget(self.comboBox_question_3, 1, 3, 1, 1)
        self.comboBox_question_4 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_question_4.setObjectName("comboBox_question_4")
        self.gridLayout_2.addWidget(self.comboBox_question_4, 1, 4, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_image_preview_text = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_image_preview_text.setObjectName("label_image_preview_text")
        self.gridLayout_3.addWidget(self.label_image_preview_text, 6, 0, 1, 1)
        self.label_image_list = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_image_list.setObjectName("label_image_list")
        self.gridLayout_3.addWidget(self.label_image_list, 0, 0, 1, 1)
        self.label_image_preview = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image_preview.sizePolicy().hasHeightForWidth())
        self.label_image_preview.setSizePolicy(sizePolicy)
        self.label_image_preview.setScaledContents(False)
        self.label_image_preview.setObjectName("label_image_preview")
        self.gridLayout_3.addWidget(self.label_image_preview, 7, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button_delete_image = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_delete_image.setObjectName("button_delete_image")
        self.verticalLayout_3.addWidget(self.button_delete_image)
        self.button_import_image = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_import_image.setObjectName("button_import_image")
        self.verticalLayout_3.addWidget(self.button_import_image)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 4, 1, 1, 1)
        self.list_weight_image = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.list_weight_image.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_weight_image.sizePolicy().hasHeightForWidth())
        self.list_weight_image.setSizePolicy(sizePolicy)
        self.list_weight_image.setObjectName("list_weight_image")
        self.gridLayout_3.addWidget(self.list_weight_image, 4, 0, 1, 1)
        self.button_add_question = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_add_question.setObjectName("button_add_question")
        self.gridLayout_3.addWidget(self.button_add_question, 7, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 2, 2, 1, 1)
        self.label_add_edit_question = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(18)
        self.label_add_edit_question.setFont(font)
        self.label_add_edit_question.setAlignment(QtCore.Qt.AlignCenter)
        self.label_add_edit_question.setObjectName("label_add_edit_question")
        self.gridLayout.addWidget(self.label_add_edit_question, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.text_edit_question = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.text_edit_question.setObjectName("text_edit_question")
        self.verticalLayout_5.addWidget(self.text_edit_question)
        self.gridLayout.addLayout(self.verticalLayout_5, 2, 1, 1, 1)
        self.list_weight_question = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.list_weight_question.setObjectName("list_weight_question")
        self.gridLayout.addWidget(self.list_weight_question, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 907, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_question_list.setText(_translate("MainWindow", "題目列表"))
        self.label_question_type_3.setText(_translate("MainWindow", "主題"))
        self.label_question_type_1.setText(_translate("MainWindow", "題型 - 一"))
        self.label_question_type_0.setText(_translate("MainWindow", "科目"))
        self.label_question_type_2.setText(_translate("MainWindow", "題型 - 二"))
        self.label_question_type_4.setText(_translate("MainWindow", "題型 - 三"))
        self.label_image_preview_text.setText(_translate("MainWindow", "圖片預覽"))
        self.label_image_list.setText(_translate("MainWindow", "圖片列表"))
        self.label_image_preview.setText(_translate("MainWindow", "TextLabel"))
        self.button_delete_image.setText(_translate("MainWindow", "刪除圖片"))
        self.button_import_image.setText(_translate("MainWindow", "匯入圖片"))
        self.button_add_question.setText(_translate("MainWindow", "新增題目"))
        self.label_add_edit_question.setText(_translate("MainWindow", "新增題目"))
        self.label_3.setText(_translate("MainWindow", "題目內容"))


