# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Make_Question_Page_UI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 50, 571, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_confirm = QtWidgets.QPushButton(self.centralwidget)
        self.btn_confirm.setGeometry(QtCore.QRect(70, 340, 75, 23))
        self.btn_confirm.setObjectName("btn_confirm")
        self.cBox_dir1 = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_dir1.setGeometry(QtCore.QRect(60, 140, 121, 21))
        self.cBox_dir1.setObjectName("cBox_dir1")
        self.cBox_dir2 = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_dir2.setGeometry(QtCore.QRect(210, 140, 121, 21))
        self.cBox_dir2.setObjectName("cBox_dir2")
        self.cBox_word = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_word.setGeometry(QtCore.QRect(360, 140, 191, 21))
        self.cBox_word.setObjectName("cBox_word")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 120, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 120, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 120, 71, 16))
        self.label_4.setObjectName("label_4")
        self.cBox_level2 = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_level2.setGeometry(QtCore.QRect(200, 230, 121, 21))
        self.cBox_level2.setObjectName("cBox_level2")
        self.label_level2 = QtWidgets.QLabel(self.centralwidget)
        self.label_level2.setGeometry(QtCore.QRect(200, 205, 71, 21))
        self.label_level2.setObjectName("label_level2")
        self.cBox_level3 = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_level3.setGeometry(QtCore.QRect(340, 230, 121, 21))
        self.cBox_level3.setObjectName("cBox_level3")
        self.label_level3 = QtWidgets.QLabel(self.centralwidget)
        self.label_level3.setGeometry(QtCore.QRect(340, 205, 71, 21))
        self.label_level3.setObjectName("label_level3")
        self.cBox_level4 = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_level4.setGeometry(QtCore.QRect(480, 230, 121, 21))
        self.cBox_level4.setObjectName("cBox_level4")
        self.label_level4 = QtWidgets.QLabel(self.centralwidget)
        self.label_level4.setGeometry(QtCore.QRect(480, 205, 71, 21))
        self.label_level4.setObjectName("label_level4")
        self.cBox_level5 = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_level5.setGeometry(QtCore.QRect(620, 230, 121, 21))
        self.cBox_level5.setObjectName("cBox_level5")
        self.label_level5 = QtWidgets.QLabel(self.centralwidget)
        self.label_level5.setGeometry(QtCore.QRect(620, 205, 71, 21))
        self.label_level5.setObjectName("label_level5")
        self.label_level1 = QtWidgets.QLabel(self.centralwidget)
        self.label_level1.setGeometry(QtCore.QRect(60, 200, 119, 23))
        self.label_level1.setObjectName("label_level1")
        self.cBox_level1 = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_level1.setGeometry(QtCore.QRect(60, 230, 119, 20))
        self.cBox_level1.setObjectName("cBox_level1")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Question Database"))
        self.label.setText(_translate("MainWindow", "請選擇試題範圍"))
        self.btn_confirm.setText(_translate("MainWindow", "確定"))
        self.label_2.setText(_translate("MainWindow", "資料夾 一層"))
        self.label_3.setText(_translate("MainWindow", "資料夾 二層"))
        self.label_4.setText(_translate("MainWindow", "Word"))
        self.label_level2.setText(_translate("MainWindow", "資料夾 二層"))
        self.label_level3.setText(_translate("MainWindow", "資料夾 三層"))
        self.label_level4.setText(_translate("MainWindow", "資料夾 四層"))
        self.label_level5.setText(_translate("MainWindow", "資料夾 五層"))
        self.label_level1.setText(_translate("MainWindow", "資料夾 一層"))


