# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Select_Question_UI.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class SelectQuestion_UI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 682)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(1)
        self.gridLayout_3.setVerticalSpacing(3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setVerticalSpacing(24)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_lv3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_lv3.setObjectName("verticalLayout_lv3")
        self.gridLayout.addLayout(self.verticalLayout_lv3, 5, 2, 1, 1)
        self.verticalLayout_lv2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_lv2.setObjectName("verticalLayout_lv2")
        self.gridLayout.addLayout(self.verticalLayout_lv2, 5, 1, 1, 1)
        self.checkBox_level1_selectAll = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(15)
        self.checkBox_level1_selectAll.setFont(font)
        self.checkBox_level1_selectAll.setObjectName("checkBox_level1_selectAll")
        self.gridLayout.addWidget(self.checkBox_level1_selectAll, 0, 0, 1, 1)
        self.verticalLayout_lv1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_lv1.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_lv1.setSpacing(6)
        self.verticalLayout_lv1.setObjectName("verticalLayout_lv1")
        self.gridLayout.addLayout(self.verticalLayout_lv1, 5, 0, 1, 1)
        self.verticalLayout_lv5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_lv5.setObjectName("verticalLayout_lv5")
        self.gridLayout.addLayout(self.verticalLayout_lv5, 5, 4, 1, 1)
        self.verticalLayout_lv4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_lv4.setObjectName("verticalLayout_lv4")
        self.gridLayout.addLayout(self.verticalLayout_lv4, 5, 3, 1, 1)
        self.checkBox_level2_selectAll = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(15)
        self.checkBox_level2_selectAll.setFont(font)
        self.checkBox_level2_selectAll.setObjectName("checkBox_level2_selectAll")
        self.gridLayout.addWidget(self.checkBox_level2_selectAll, 0, 1, 1, 1)
        self.checkBox_level3_selectAll = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(15)
        self.checkBox_level3_selectAll.setFont(font)
        self.checkBox_level3_selectAll.setObjectName("checkBox_level3_selectAll")
        self.gridLayout.addWidget(self.checkBox_level3_selectAll, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 4, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.button_add_unit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        self.button_add_unit.setFont(font)
        self.button_add_unit.setObjectName("button_add_unit")
        self.horizontalLayout_7.addWidget(self.button_add_unit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.button_add_question = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        self.button_add_question.setFont(font)
        self.button_add_question.setObjectName("button_add_question")
        self.horizontalLayout_7.addWidget(self.button_add_question)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.button_make_question = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        self.button_make_question.setFont(font)
        self.button_make_question.setObjectName("button_make_question")
        self.horizontalLayout_7.addWidget(self.button_make_question)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_return = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_return.sizePolicy().hasHeightForWidth())
        self.button_return.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_return.setFont(font)
        self.button_return.setObjectName("button_return")
        self.horizontalLayout_2.addWidget(self.button_return)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_add_edit_question = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_add_edit_question.setFont(font)
        self.label_add_edit_question.setAlignment(QtCore.Qt.AlignCenter)
        self.label_add_edit_question.setObjectName("label_add_edit_question")
        self.gridLayout_2.addWidget(self.label_add_edit_question, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_level1_selectAll.setText(_translate("MainWindow", "全選"))
        self.checkBox_level2_selectAll.setText(_translate("MainWindow", "全選"))
        self.checkBox_level3_selectAll.setText(_translate("MainWindow", "全選"))
        self.button_add_unit.setText(_translate("MainWindow", "新增單元"))
        self.button_add_question.setText(_translate("MainWindow", "新增題目"))
        self.button_make_question.setText(_translate("MainWindow", "出題"))
        self.button_return.setText(_translate("MainWindow", "返回選擇科目"))
        self.label_add_edit_question.setText(_translate("MainWindow", "選擇題目階層"))


